### ISSUE TITLE
Add content command

### ISSUE THREAD

**Issue by quba42** [pulp/pulp-cli-deb#23]
The CLI for RPM knows the content sub command (for listing various content etc.)
We should provide similar functionality for deb!

**Comment by quba42** [comment]
This has at least some overlap with issue #20!

**Comment by daviddavis** [comment]
This is a major gap that I keep running into. 😢

**Comment by hstct** [comment]
I'm currently working on implementing this command though it is a learning experience. I'm not too familiar with the cli implementation :)
